name: AlitaPomodoro
options:
  bundleIdPrefix: com.alita
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  AlitaPomodoro:
    type: application
    platform: macOS
    sources:
      - path: AlitaPomodoro/Sources
      - path: AlitaPomodoro/Resources
    settings:
      base:
        PRODUCT_NAME: AlitaPomodoro
        PRODUCT_BUNDLE_IDENTIFIER: com.alita.pomodoro
        INFOPLIST_FILE: AlitaPomodoro/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: AlitaPomodoro/Resources/AlitaPomodoro.entitlements
        ICON_FILE: "AppIcon"
