name: LolitaPomodoro
options:
  bundleIdPrefix: com.lolita
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  LolitaPomodoro:
    type: application
    platform: macOS
    sources:
      - path: LolitaPomodoro/Sources
      - path: LolitaPomodoro/Resources
    settings:
      base:
        PRODUCT_NAME: LolitaPomodoro
        PRODUCT_BUNDLE_IDENTIFIER: com.lolita.pomodoro
        INFOPLIST_FILE: LolitaPomodoro/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: LolitaPomodoro/Resources/LolitaPomodoro.entitlements
        ICON_FILE: "AppIcon"
